# так же берём готовый контейнер с node на основе alpine
FROM node:20-alpine
# Задаем рабочий каталог
WORKDIR /usr/src/app
# Копируем туда наши json файлы
ADD *.json ./
# Устанавливаем все пакеты и зависимости указанные в json
RUN npm install --legacy-peer-deps

ADD ./public ./public
ADD ./src ./src

CMD npm start