# Generated by Django 3.2 on 2024-05-28 09:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='History_project',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000, unique=True)),
                ('photo', models.TextField(null=True)),
                ('description', models.TextField()),
                ('count', models.IntegerField()),
                ('status', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project_details',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='students.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SelectedProject',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='students.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('skill', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Skills_students',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.FloatField(blank=True)),
                ('discipline', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='students.discipline')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='students.skill')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_student', models.BooleanField(default=False)),
                ('is_teacher', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('projects', models.ManyToManyField(through='students.Project_details', to='students.Project')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='teacher', to='students.user')),
            ],
        ),
        migrations.CreateModel(
            name='Tag_project',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='students.project')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='students.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('direction', models.CharField(max_length=255)),
                ('course', models.IntegerField()),
                ('is_study', models.BooleanField()),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('projects', models.ManyToManyField(through='students.History_project', to='students.Project')),
                ('selected_projects', models.ManyToManyField(related_name='students_projects', through='students.SelectedProject', to='students.Project')),
                ('skills', models.ManyToManyField(through='students.Skills_students', to='students.Skill')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='student', to='students.user')),
            ],
        ),
        migrations.CreateModel(
            name='Skills_weight',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight_skill', models.FloatField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='students.project')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='students.skill')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='skills_students',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='students.student'),
        ),
        migrations.AddField(
            model_name='selectedproject',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='students.student'),
        ),
        migrations.AddField(
            model_name='project_details',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='students.teacher'),
        ),
        migrations.AddField(
            model_name='project',
            name='selected_projects',
            field=models.ManyToManyField(related_name='students_projects', through='students.SelectedProject', to='students.Student'),
        ),
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(blank=True, through='students.Skills_weight', to='students.Skill'),
        ),
        migrations.AddField(
            model_name='project',
            name='students',
            field=models.ManyToManyField(through='students.History_project', to='students.Student'),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(through='students.Tag_project', to='students.Tag'),
        ),
        migrations.AddField(
            model_name='project',
            name='teachers',
            field=models.ManyToManyField(blank=True, through='students.Project_details', to='students.Teacher'),
        ),
        migrations.AddField(
            model_name='history_project',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='students.project'),
        ),
        migrations.AddField(
            model_name='history_project',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='students.student'),
        ),
        migrations.CreateModel(
            name='AccompDoc',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('implementation', models.BooleanField()),
                ('publication', models.BooleanField()),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='students.discipline')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='students.student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
